version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-api-service
    ports:
      - "80:4000"
  flask-api-service:
    build: "../flask-api-service"
      # ... other environment variables
    ports:
      - "5000"