version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-api-service-1
      - flask-api-service-2
      - flask-api-service-3
      - flask-api-service-4
    ports:
      - "80:4000"